### ISSUE TITLE
Alter table syntax into create table.

### ISSUE THREAD

**Issue by andyg2** [ww9/mysql2sqlite#6]
I've used your excellent converter but I've hit a snag.
My SQL dumps separate the keys assignments into separate ALTER TABLE queries.

Is there any way I can a) force my dumps to not do this, or b) is there a way to integrate them into the CREATE TABLE query, or c) are there plans to include this in the script?

Example
`ALTER TABLE `grid_lines` ADD PRIMARY KEY (`lineID`), ADD KEY `cameraID` (`cameraID`);`

**Comment by ww9** [comment]
Hi Andy, thanks for the compliment!
I'm sure there is a way to integrate KEYS into CREATE TALBLE in the output but currently I'm afraid that I cannot take a closer look at the issue.
I wrote this tool in a hurry, it could use some refactoring and then these issues could be addressed in an easier fashion.

**Comment by andyg2** [comment]
> I wrote this tool in a hurry, it could use some refactoring and then these issues could be addressed in an easier fashion.

Sure I understand, I know the feeling all too well :)
